### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [johyemtol/CPP202309#1]
### 없는 파일
- challenge/week2/temperature2.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week6/tic_tac_toe.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

**Comment by johyemtol** [comment]
#1
